title: Prof. Olgierd Unold
logo: /assets/images/ounold.png
#description: Research Scientist at [WUT](https://pwr.edu.pl/)
theme: jekyll-theme-minimal
#show_downloads: true
google_analytics: G-L1218Z6MX8
url: "https://ounold.github.io"
